package br.ufc.model;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lixeiras.proto

public final class Lixeiras {
  private Lixeiras() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LixeiraOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Lixeira)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required string localizacao = 2;</code>
     */
    boolean hasLocalizacao();
    /**
     * <code>required string localizacao = 2;</code>
     */
    java.lang.String getLocalizacao();
    /**
     * <code>required string localizacao = 2;</code>
     */
    com.google.protobuf.ByteString
        getLocalizacaoBytes();

    /**
     * <code>required float peso = 3;</code>
     */
    boolean hasPeso();
    /**
     * <code>required float peso = 3;</code>
     */
    float getPeso();

    /**
     * <code>required .Lixeira.StatusColeta status_coleta = 4 [default = LIVRE];</code>
     */
    boolean hasStatusColeta();
    /**
     * <code>required .Lixeira.StatusColeta status_coleta = 4 [default = LIVRE];</code>
     */
    Lixeiras.Lixeira.StatusColeta getStatusColeta();

    /**
     * <code>required .Lixeira.StatusCapacidade status_capacidade = 5 [default = VAZIA];</code>
     */
    boolean hasStatusCapacidade();
    /**
     * <code>required .Lixeira.StatusCapacidade status_capacidade = 5 [default = VAZIA];</code>
     */
    Lixeiras.Lixeira.StatusCapacidade getStatusCapacidade();
  }
  /**
   * Protobuf type {@code Lixeira}
   */
  public  static final class Lixeira extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Lixeira)
      LixeiraOrBuilder {
    // Use Lixeira.newBuilder() to construct.
    private Lixeira(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Lixeira() {
      id_ = 0;
      localizacao_ = "";
      peso_ = 0F;
      statusColeta_ = 1;
      statusCapacidade_ = 1;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Lixeira(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              localizacao_ = bs;
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              peso_ = input.readFloat();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              Lixeiras.Lixeira.StatusColeta value = Lixeiras.Lixeira.StatusColeta.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                statusColeta_ = rawValue;
              }
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              Lixeiras.Lixeira.StatusCapacidade value = Lixeiras.Lixeira.StatusCapacidade.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                statusCapacidade_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Lixeiras.internal_static_Lixeira_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Lixeiras.internal_static_Lixeira_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Lixeiras.Lixeira.class, Lixeiras.Lixeira.Builder.class);
    }

    /**
     * Protobuf enum {@code Lixeira.StatusColeta}
     */
    public enum StatusColeta
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ROTA = 0;</code>
       */
      ROTA(0),
      /**
       * <code>LIVRE = 1;</code>
       */
      LIVRE(1),
      ;

      /**
       * <code>ROTA = 0;</code>
       */
      public static final int ROTA_VALUE = 0;
      /**
       * <code>LIVRE = 1;</code>
       */
      public static final int LIVRE_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static StatusColeta valueOf(int value) {
        return forNumber(value);
      }

      public static StatusColeta forNumber(int value) {
        switch (value) {
          case 0: return ROTA;
          case 1: return LIVRE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<StatusColeta>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          StatusColeta> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<StatusColeta>() {
              public StatusColeta findValueByNumber(int number) {
                return StatusColeta.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Lixeiras.Lixeira.getDescriptor().getEnumTypes().get(0);
      }

      private static final StatusColeta[] VALUES = values();

      public static StatusColeta valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private StatusColeta(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Lixeira.StatusColeta)
    }

    /**
     * Protobuf enum {@code Lixeira.StatusCapacidade}
     */
    public enum StatusCapacidade
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CHEIA = 0;</code>
       */
      CHEIA(0),
      /**
       * <code>VAZIA = 1;</code>
       */
      VAZIA(1),
      ;

      /**
       * <code>CHEIA = 0;</code>
       */
      public static final int CHEIA_VALUE = 0;
      /**
       * <code>VAZIA = 1;</code>
       */
      public static final int VAZIA_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static StatusCapacidade valueOf(int value) {
        return forNumber(value);
      }

      public static StatusCapacidade forNumber(int value) {
        switch (value) {
          case 0: return CHEIA;
          case 1: return VAZIA;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<StatusCapacidade>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          StatusCapacidade> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<StatusCapacidade>() {
              public StatusCapacidade findValueByNumber(int number) {
                return StatusCapacidade.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Lixeiras.Lixeira.getDescriptor().getEnumTypes().get(1);
      }

      private static final StatusCapacidade[] VALUES = values();

      public static StatusCapacidade valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private StatusCapacidade(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Lixeira.StatusCapacidade)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int LOCALIZACAO_FIELD_NUMBER = 2;
    private volatile java.lang.Object localizacao_;
    /**
     * <code>required string localizacao = 2;</code>
     */
    public boolean hasLocalizacao() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string localizacao = 2;</code>
     */
    public java.lang.String getLocalizacao() {
      java.lang.Object ref = localizacao_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          localizacao_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string localizacao = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLocalizacaoBytes() {
      java.lang.Object ref = localizacao_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localizacao_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PESO_FIELD_NUMBER = 3;
    private float peso_;
    /**
     * <code>required float peso = 3;</code>
     */
    public boolean hasPeso() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float peso = 3;</code>
     */
    public float getPeso() {
      return peso_;
    }

    public static final int STATUS_COLETA_FIELD_NUMBER = 4;
    private int statusColeta_;
    /**
     * <code>required .Lixeira.StatusColeta status_coleta = 4 [default = LIVRE];</code>
     */
    public boolean hasStatusColeta() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .Lixeira.StatusColeta status_coleta = 4 [default = LIVRE];</code>
     */
    public Lixeiras.Lixeira.StatusColeta getStatusColeta() {
      Lixeiras.Lixeira.StatusColeta result = Lixeiras.Lixeira.StatusColeta.valueOf(statusColeta_);
      return result == null ? Lixeiras.Lixeira.StatusColeta.LIVRE : result;
    }

    public static final int STATUS_CAPACIDADE_FIELD_NUMBER = 5;
    private int statusCapacidade_;
    /**
     * <code>required .Lixeira.StatusCapacidade status_capacidade = 5 [default = VAZIA];</code>
     */
    public boolean hasStatusCapacidade() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required .Lixeira.StatusCapacidade status_capacidade = 5 [default = VAZIA];</code>
     */
    public Lixeiras.Lixeira.StatusCapacidade getStatusCapacidade() {
      Lixeiras.Lixeira.StatusCapacidade result = Lixeiras.Lixeira.StatusCapacidade.valueOf(statusCapacidade_);
      return result == null ? Lixeiras.Lixeira.StatusCapacidade.VAZIA : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocalizacao()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPeso()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatusColeta()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatusCapacidade()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, localizacao_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, peso_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, statusColeta_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, statusCapacidade_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, localizacao_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, peso_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, statusColeta_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, statusCapacidade_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Lixeiras.Lixeira)) {
        return super.equals(obj);
      }
      Lixeiras.Lixeira other = (Lixeiras.Lixeira) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasLocalizacao() == other.hasLocalizacao());
      if (hasLocalizacao()) {
        result = result && getLocalizacao()
            .equals(other.getLocalizacao());
      }
      result = result && (hasPeso() == other.hasPeso());
      if (hasPeso()) {
        result = result && (
            java.lang.Float.floatToIntBits(getPeso())
            == java.lang.Float.floatToIntBits(
                other.getPeso()));
      }
      result = result && (hasStatusColeta() == other.hasStatusColeta());
      if (hasStatusColeta()) {
        result = result && statusColeta_ == other.statusColeta_;
      }
      result = result && (hasStatusCapacidade() == other.hasStatusCapacidade());
      if (hasStatusCapacidade()) {
        result = result && statusCapacidade_ == other.statusCapacidade_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasLocalizacao()) {
        hash = (37 * hash) + LOCALIZACAO_FIELD_NUMBER;
        hash = (53 * hash) + getLocalizacao().hashCode();
      }
      if (hasPeso()) {
        hash = (37 * hash) + PESO_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getPeso());
      }
      if (hasStatusColeta()) {
        hash = (37 * hash) + STATUS_COLETA_FIELD_NUMBER;
        hash = (53 * hash) + statusColeta_;
      }
      if (hasStatusCapacidade()) {
        hash = (37 * hash) + STATUS_CAPACIDADE_FIELD_NUMBER;
        hash = (53 * hash) + statusCapacidade_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Lixeiras.Lixeira parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Lixeiras.Lixeira parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Lixeiras.Lixeira parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Lixeiras.Lixeira parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Lixeiras.Lixeira parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Lixeiras.Lixeira parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Lixeiras.Lixeira parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Lixeiras.Lixeira parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Lixeiras.Lixeira parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Lixeiras.Lixeira parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Lixeiras.Lixeira prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Lixeira}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Lixeira)
        Lixeiras.LixeiraOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Lixeiras.internal_static_Lixeira_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Lixeiras.internal_static_Lixeira_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Lixeiras.Lixeira.class, Lixeiras.Lixeira.Builder.class);
      }

      // Construct using Lixeiras.Lixeira.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        localizacao_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        peso_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        statusColeta_ = 1;
        bitField0_ = (bitField0_ & ~0x00000008);
        statusCapacidade_ = 1;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Lixeiras.internal_static_Lixeira_descriptor;
      }

      public Lixeiras.Lixeira getDefaultInstanceForType() {
        return Lixeiras.Lixeira.getDefaultInstance();
      }

      public Lixeiras.Lixeira build() {
        Lixeiras.Lixeira result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Lixeiras.Lixeira buildPartial() {
        Lixeiras.Lixeira result = new Lixeiras.Lixeira(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.localizacao_ = localizacao_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.peso_ = peso_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.statusColeta_ = statusColeta_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.statusCapacidade_ = statusCapacidade_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Lixeiras.Lixeira) {
          return mergeFrom((Lixeiras.Lixeira)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Lixeiras.Lixeira other) {
        if (other == Lixeiras.Lixeira.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasLocalizacao()) {
          bitField0_ |= 0x00000002;
          localizacao_ = other.localizacao_;
          onChanged();
        }
        if (other.hasPeso()) {
          setPeso(other.getPeso());
        }
        if (other.hasStatusColeta()) {
          setStatusColeta(other.getStatusColeta());
        }
        if (other.hasStatusCapacidade()) {
          setStatusCapacidade(other.getStatusCapacidade());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasLocalizacao()) {
          return false;
        }
        if (!hasPeso()) {
          return false;
        }
        if (!hasStatusColeta()) {
          return false;
        }
        if (!hasStatusCapacidade()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Lixeiras.Lixeira parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Lixeiras.Lixeira) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object localizacao_ = "";
      /**
       * <code>required string localizacao = 2;</code>
       */
      public boolean hasLocalizacao() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string localizacao = 2;</code>
       */
      public java.lang.String getLocalizacao() {
        java.lang.Object ref = localizacao_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            localizacao_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string localizacao = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLocalizacaoBytes() {
        java.lang.Object ref = localizacao_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          localizacao_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string localizacao = 2;</code>
       */
      public Builder setLocalizacao(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        localizacao_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string localizacao = 2;</code>
       */
      public Builder clearLocalizacao() {
        bitField0_ = (bitField0_ & ~0x00000002);
        localizacao_ = getDefaultInstance().getLocalizacao();
        onChanged();
        return this;
      }
      /**
       * <code>required string localizacao = 2;</code>
       */
      public Builder setLocalizacaoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        localizacao_ = value;
        onChanged();
        return this;
      }

      private float peso_ ;
      /**
       * <code>required float peso = 3;</code>
       */
      public boolean hasPeso() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float peso = 3;</code>
       */
      public float getPeso() {
        return peso_;
      }
      /**
       * <code>required float peso = 3;</code>
       */
      public Builder setPeso(float value) {
        bitField0_ |= 0x00000004;
        peso_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float peso = 3;</code>
       */
      public Builder clearPeso() {
        bitField0_ = (bitField0_ & ~0x00000004);
        peso_ = 0F;
        onChanged();
        return this;
      }

      private int statusColeta_ = 1;
      /**
       * <code>required .Lixeira.StatusColeta status_coleta = 4 [default = LIVRE];</code>
       */
      public boolean hasStatusColeta() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .Lixeira.StatusColeta status_coleta = 4 [default = LIVRE];</code>
       */
      public Lixeiras.Lixeira.StatusColeta getStatusColeta() {
        Lixeiras.Lixeira.StatusColeta result = Lixeiras.Lixeira.StatusColeta.valueOf(statusColeta_);
        return result == null ? Lixeiras.Lixeira.StatusColeta.LIVRE : result;
      }
      /**
       * <code>required .Lixeira.StatusColeta status_coleta = 4 [default = LIVRE];</code>
       */
      public Builder setStatusColeta(Lixeiras.Lixeira.StatusColeta value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        statusColeta_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .Lixeira.StatusColeta status_coleta = 4 [default = LIVRE];</code>
       */
      public Builder clearStatusColeta() {
        bitField0_ = (bitField0_ & ~0x00000008);
        statusColeta_ = 1;
        onChanged();
        return this;
      }

      private int statusCapacidade_ = 1;
      /**
       * <code>required .Lixeira.StatusCapacidade status_capacidade = 5 [default = VAZIA];</code>
       */
      public boolean hasStatusCapacidade() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .Lixeira.StatusCapacidade status_capacidade = 5 [default = VAZIA];</code>
       */
      public Lixeiras.Lixeira.StatusCapacidade getStatusCapacidade() {
        Lixeiras.Lixeira.StatusCapacidade result = Lixeiras.Lixeira.StatusCapacidade.valueOf(statusCapacidade_);
        return result == null ? Lixeiras.Lixeira.StatusCapacidade.VAZIA : result;
      }
      /**
       * <code>required .Lixeira.StatusCapacidade status_capacidade = 5 [default = VAZIA];</code>
       */
      public Builder setStatusCapacidade(Lixeiras.Lixeira.StatusCapacidade value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        statusCapacidade_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .Lixeira.StatusCapacidade status_capacidade = 5 [default = VAZIA];</code>
       */
      public Builder clearStatusCapacidade() {
        bitField0_ = (bitField0_ & ~0x00000010);
        statusCapacidade_ = 1;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Lixeira)
    }

    // @@protoc_insertion_point(class_scope:Lixeira)
    private static final Lixeiras.Lixeira DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Lixeiras.Lixeira();
    }

    public static Lixeiras.Lixeira getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Lixeira>
        PARSER = new com.google.protobuf.AbstractParser<Lixeira>() {
      public Lixeira parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Lixeira(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Lixeira> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Lixeira> getParserForType() {
      return PARSER;
    }

    public Lixeiras.Lixeira getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ListaLixeiraOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ListaLixeira)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Lixeira lixeira = 1;</code>
     */
    java.util.List<Lixeiras.Lixeira> 
        getLixeiraList();
    /**
     * <code>repeated .Lixeira lixeira = 1;</code>
     */
    Lixeiras.Lixeira getLixeira(int index);
    /**
     * <code>repeated .Lixeira lixeira = 1;</code>
     */
    int getLixeiraCount();
    /**
     * <code>repeated .Lixeira lixeira = 1;</code>
     */
    java.util.List<? extends Lixeiras.LixeiraOrBuilder> 
        getLixeiraOrBuilderList();
    /**
     * <code>repeated .Lixeira lixeira = 1;</code>
     */
    Lixeiras.LixeiraOrBuilder getLixeiraOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ListaLixeira}
   */
  public  static final class ListaLixeira extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ListaLixeira)
      ListaLixeiraOrBuilder {
    // Use ListaLixeira.newBuilder() to construct.
    private ListaLixeira(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ListaLixeira() {
      lixeira_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ListaLixeira(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                lixeira_ = new java.util.ArrayList<Lixeiras.Lixeira>();
                mutable_bitField0_ |= 0x00000001;
              }
              lixeira_.add(
                  input.readMessage(Lixeiras.Lixeira.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          lixeira_ = java.util.Collections.unmodifiableList(lixeira_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Lixeiras.internal_static_ListaLixeira_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Lixeiras.internal_static_ListaLixeira_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Lixeiras.ListaLixeira.class, Lixeiras.ListaLixeira.Builder.class);
    }

    public static final int LIXEIRA_FIELD_NUMBER = 1;
    private java.util.List<Lixeiras.Lixeira> lixeira_;
    /**
     * <code>repeated .Lixeira lixeira = 1;</code>
     */
    public java.util.List<Lixeiras.Lixeira> getLixeiraList() {
      return lixeira_;
    }
    /**
     * <code>repeated .Lixeira lixeira = 1;</code>
     */
    public java.util.List<? extends Lixeiras.LixeiraOrBuilder> 
        getLixeiraOrBuilderList() {
      return lixeira_;
    }
    /**
     * <code>repeated .Lixeira lixeira = 1;</code>
     */
    public int getLixeiraCount() {
      return lixeira_.size();
    }
    /**
     * <code>repeated .Lixeira lixeira = 1;</code>
     */
    public Lixeiras.Lixeira getLixeira(int index) {
      return lixeira_.get(index);
    }
    /**
     * <code>repeated .Lixeira lixeira = 1;</code>
     */
    public Lixeiras.LixeiraOrBuilder getLixeiraOrBuilder(
        int index) {
      return lixeira_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getLixeiraCount(); i++) {
        if (!getLixeira(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < lixeira_.size(); i++) {
        output.writeMessage(1, lixeira_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < lixeira_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, lixeira_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Lixeiras.ListaLixeira)) {
        return super.equals(obj);
      }
      Lixeiras.ListaLixeira other = (Lixeiras.ListaLixeira) obj;

      boolean result = true;
      result = result && getLixeiraList()
          .equals(other.getLixeiraList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getLixeiraCount() > 0) {
        hash = (37 * hash) + LIXEIRA_FIELD_NUMBER;
        hash = (53 * hash) + getLixeiraList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Lixeiras.ListaLixeira parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Lixeiras.ListaLixeira parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Lixeiras.ListaLixeira parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Lixeiras.ListaLixeira parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Lixeiras.ListaLixeira parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Lixeiras.ListaLixeira parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Lixeiras.ListaLixeira parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Lixeiras.ListaLixeira parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Lixeiras.ListaLixeira parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Lixeiras.ListaLixeira parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Lixeiras.ListaLixeira prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ListaLixeira}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ListaLixeira)
        Lixeiras.ListaLixeiraOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Lixeiras.internal_static_ListaLixeira_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Lixeiras.internal_static_ListaLixeira_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Lixeiras.ListaLixeira.class, Lixeiras.ListaLixeira.Builder.class);
      }

      // Construct using Lixeiras.ListaLixeira.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLixeiraFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (lixeiraBuilder_ == null) {
          lixeira_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          lixeiraBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Lixeiras.internal_static_ListaLixeira_descriptor;
      }

      public Lixeiras.ListaLixeira getDefaultInstanceForType() {
        return Lixeiras.ListaLixeira.getDefaultInstance();
      }

      public Lixeiras.ListaLixeira build() {
        Lixeiras.ListaLixeira result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Lixeiras.ListaLixeira buildPartial() {
        Lixeiras.ListaLixeira result = new Lixeiras.ListaLixeira(this);
        int from_bitField0_ = bitField0_;
        if (lixeiraBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            lixeira_ = java.util.Collections.unmodifiableList(lixeira_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.lixeira_ = lixeira_;
        } else {
          result.lixeira_ = lixeiraBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Lixeiras.ListaLixeira) {
          return mergeFrom((Lixeiras.ListaLixeira)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Lixeiras.ListaLixeira other) {
        if (other == Lixeiras.ListaLixeira.getDefaultInstance()) return this;
        if (lixeiraBuilder_ == null) {
          if (!other.lixeira_.isEmpty()) {
            if (lixeira_.isEmpty()) {
              lixeira_ = other.lixeira_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLixeiraIsMutable();
              lixeira_.addAll(other.lixeira_);
            }
            onChanged();
          }
        } else {
          if (!other.lixeira_.isEmpty()) {
            if (lixeiraBuilder_.isEmpty()) {
              lixeiraBuilder_.dispose();
              lixeiraBuilder_ = null;
              lixeira_ = other.lixeira_;
              bitField0_ = (bitField0_ & ~0x00000001);
              lixeiraBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLixeiraFieldBuilder() : null;
            } else {
              lixeiraBuilder_.addAllMessages(other.lixeira_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getLixeiraCount(); i++) {
          if (!getLixeira(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Lixeiras.ListaLixeira parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Lixeiras.ListaLixeira) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Lixeiras.Lixeira> lixeira_ =
        java.util.Collections.emptyList();
      private void ensureLixeiraIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          lixeira_ = new java.util.ArrayList<Lixeiras.Lixeira>(lixeira_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Lixeiras.Lixeira, Lixeiras.Lixeira.Builder, Lixeiras.LixeiraOrBuilder> lixeiraBuilder_;

      /**
       * <code>repeated .Lixeira lixeira = 1;</code>
       */
      public java.util.List<Lixeiras.Lixeira> getLixeiraList() {
        if (lixeiraBuilder_ == null) {
          return java.util.Collections.unmodifiableList(lixeira_);
        } else {
          return lixeiraBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Lixeira lixeira = 1;</code>
       */
      public int getLixeiraCount() {
        if (lixeiraBuilder_ == null) {
          return lixeira_.size();
        } else {
          return lixeiraBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Lixeira lixeira = 1;</code>
       */
      public Lixeiras.Lixeira getLixeira(int index) {
        if (lixeiraBuilder_ == null) {
          return lixeira_.get(index);
        } else {
          return lixeiraBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Lixeira lixeira = 1;</code>
       */
      public Builder setLixeira(
          int index, Lixeiras.Lixeira value) {
        if (lixeiraBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLixeiraIsMutable();
          lixeira_.set(index, value);
          onChanged();
        } else {
          lixeiraBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Lixeira lixeira = 1;</code>
       */
      public Builder setLixeira(
          int index, Lixeiras.Lixeira.Builder builderForValue) {
        if (lixeiraBuilder_ == null) {
          ensureLixeiraIsMutable();
          lixeira_.set(index, builderForValue.build());
          onChanged();
        } else {
          lixeiraBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Lixeira lixeira = 1;</code>
       */
      public Builder addLixeira(Lixeiras.Lixeira value) {
        if (lixeiraBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLixeiraIsMutable();
          lixeira_.add(value);
          onChanged();
        } else {
          lixeiraBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Lixeira lixeira = 1;</code>
       */
      public Builder addLixeira(
          int index, Lixeiras.Lixeira value) {
        if (lixeiraBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLixeiraIsMutable();
          lixeira_.add(index, value);
          onChanged();
        } else {
          lixeiraBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Lixeira lixeira = 1;</code>
       */
      public Builder addLixeira(
          Lixeiras.Lixeira.Builder builderForValue) {
        if (lixeiraBuilder_ == null) {
          ensureLixeiraIsMutable();
          lixeira_.add(builderForValue.build());
          onChanged();
        } else {
          lixeiraBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Lixeira lixeira = 1;</code>
       */
      public Builder addLixeira(
          int index, Lixeiras.Lixeira.Builder builderForValue) {
        if (lixeiraBuilder_ == null) {
          ensureLixeiraIsMutable();
          lixeira_.add(index, builderForValue.build());
          onChanged();
        } else {
          lixeiraBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Lixeira lixeira = 1;</code>
       */
      public Builder addAllLixeira(
          java.lang.Iterable<? extends Lixeiras.Lixeira> values) {
        if (lixeiraBuilder_ == null) {
          ensureLixeiraIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, lixeira_);
          onChanged();
        } else {
          lixeiraBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Lixeira lixeira = 1;</code>
       */
      public Builder clearLixeira() {
        if (lixeiraBuilder_ == null) {
          lixeira_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          lixeiraBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Lixeira lixeira = 1;</code>
       */
      public Builder removeLixeira(int index) {
        if (lixeiraBuilder_ == null) {
          ensureLixeiraIsMutable();
          lixeira_.remove(index);
          onChanged();
        } else {
          lixeiraBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Lixeira lixeira = 1;</code>
       */
      public Lixeiras.Lixeira.Builder getLixeiraBuilder(
          int index) {
        return getLixeiraFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Lixeira lixeira = 1;</code>
       */
      public Lixeiras.LixeiraOrBuilder getLixeiraOrBuilder(
          int index) {
        if (lixeiraBuilder_ == null) {
          return lixeira_.get(index);  } else {
          return lixeiraBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Lixeira lixeira = 1;</code>
       */
      public java.util.List<? extends Lixeiras.LixeiraOrBuilder> 
           getLixeiraOrBuilderList() {
        if (lixeiraBuilder_ != null) {
          return lixeiraBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(lixeira_);
        }
      }
      /**
       * <code>repeated .Lixeira lixeira = 1;</code>
       */
      public Lixeiras.Lixeira.Builder addLixeiraBuilder() {
        return getLixeiraFieldBuilder().addBuilder(
            Lixeiras.Lixeira.getDefaultInstance());
      }
      /**
       * <code>repeated .Lixeira lixeira = 1;</code>
       */
      public Lixeiras.Lixeira.Builder addLixeiraBuilder(
          int index) {
        return getLixeiraFieldBuilder().addBuilder(
            index, Lixeiras.Lixeira.getDefaultInstance());
      }
      /**
       * <code>repeated .Lixeira lixeira = 1;</code>
       */
      public java.util.List<Lixeiras.Lixeira.Builder> 
           getLixeiraBuilderList() {
        return getLixeiraFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Lixeiras.Lixeira, Lixeiras.Lixeira.Builder, Lixeiras.LixeiraOrBuilder> 
          getLixeiraFieldBuilder() {
        if (lixeiraBuilder_ == null) {
          lixeiraBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Lixeiras.Lixeira, Lixeiras.Lixeira.Builder, Lixeiras.LixeiraOrBuilder>(
                  lixeira_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          lixeira_ = null;
        }
        return lixeiraBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ListaLixeira)
    }

    // @@protoc_insertion_point(class_scope:ListaLixeira)
    private static final Lixeiras.ListaLixeira DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Lixeiras.ListaLixeira();
    }

    public static Lixeiras.ListaLixeira getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ListaLixeira>
        PARSER = new com.google.protobuf.AbstractParser<ListaLixeira>() {
      public ListaLixeira parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ListaLixeira(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ListaLixeira> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListaLixeira> getParserForType() {
      return PARSER;
    }

    public Lixeiras.ListaLixeira getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Lixeira_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Lixeira_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListaLixeira_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListaLixeira_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016lixeiras.proto\"\371\001\n\007Lixeira\022\n\n\002id\030\001 \002(\005" +
      "\022\023\n\013localizacao\030\002 \002(\t\022\014\n\004peso\030\003 \002(\002\0223\n\rs" +
      "tatus_coleta\030\004 \002(\0162\025.Lixeira.StatusColet" +
      "a:\005LIVRE\022;\n\021status_capacidade\030\005 \002(\0162\031.Li" +
      "xeira.StatusCapacidade:\005VAZIA\"#\n\014StatusC" +
      "oleta\022\010\n\004ROTA\020\000\022\t\n\005LIVRE\020\001\"(\n\020StatusCapa" +
      "cidade\022\t\n\005CHEIA\020\000\022\t\n\005VAZIA\020\001\")\n\014ListaLix" +
      "eira\022\031\n\007lixeira\030\001 \003(\0132\010.Lixeira"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Lixeira_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Lixeira_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Lixeira_descriptor,
        new java.lang.String[] { "Id", "Localizacao", "Peso", "StatusColeta", "StatusCapacidade", });
    internal_static_ListaLixeira_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ListaLixeira_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListaLixeira_descriptor,
        new java.lang.String[] { "Lixeira", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
