package br.ufc.model;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mensagem.proto

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MensagemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Mensagem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 tipo = 1;</code>
     */
    boolean hasTipo();
    /**
     * <code>required int32 tipo = 1;</code>
     */
    int getTipo();

    /**
     * <code>required int32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 2;</code>
     */
    int getId();

    /**
     * <code>required string objeto = 3;</code>
     */
    boolean hasObjeto();
    /**
     * <code>required string objeto = 3;</code>
     */
    java.lang.String getObjeto();
    /**
     * <code>required string objeto = 3;</code>
     */
    com.google.protobuf.ByteString
        getObjetoBytes();

    /**
     * <code>required string metodo = 4;</code>
     */
    boolean hasMetodo();
    /**
     * <code>required string metodo = 4;</code>
     */
    java.lang.String getMetodo();
    /**
     * <code>required string metodo = 4;</code>
     */
    com.google.protobuf.ByteString
        getMetodoBytes();

    /**
     * <code>repeated bytes argumentos = 5;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getArgumentosList();
    /**
     * <code>repeated bytes argumentos = 5;</code>
     */
    int getArgumentosCount();
    /**
     * <code>repeated bytes argumentos = 5;</code>
     */
    com.google.protobuf.ByteString getArgumentos(int index);
  }
  /**
   * Protobuf type {@code Mensagem}
   */
  public static final class Mensagem extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Mensagem)
      MensagemOrBuilder {
    // Use Mensagem.newBuilder() to construct.
    private Mensagem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Mensagem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Mensagem defaultInstance;
    public static Mensagem getDefaultInstance() {
      return defaultInstance;
    }

    public Mensagem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Mensagem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              tipo_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              objeto_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              metodo_ = bs;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                argumentos_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000010;
              }
              argumentos_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          argumentos_ = java.util.Collections.unmodifiableList(argumentos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Message.internal_static_Mensagem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Message.internal_static_Mensagem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.Mensagem.class, Message.Mensagem.Builder.class);
    }

    public static com.google.protobuf.Parser<Mensagem> PARSER =
        new com.google.protobuf.AbstractParser<Mensagem>() {
      public Mensagem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Mensagem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Mensagem> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TIPO_FIELD_NUMBER = 1;
    private int tipo_;
    /**
     * <code>required int32 tipo = 1;</code>
     */
    public boolean hasTipo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 tipo = 1;</code>
     */
    public int getTipo() {
      return tipo_;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>required int32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int OBJETO_FIELD_NUMBER = 3;
    private java.lang.Object objeto_;
    /**
     * <code>required string objeto = 3;</code>
     */
    public boolean hasObjeto() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string objeto = 3;</code>
     */
    public java.lang.String getObjeto() {
      java.lang.Object ref = objeto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          objeto_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string objeto = 3;</code>
     */
    public com.google.protobuf.ByteString
        getObjetoBytes() {
      java.lang.Object ref = objeto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objeto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METODO_FIELD_NUMBER = 4;
    private java.lang.Object metodo_;
    /**
     * <code>required string metodo = 4;</code>
     */
    public boolean hasMetodo() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string metodo = 4;</code>
     */
    public java.lang.String getMetodo() {
      java.lang.Object ref = metodo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          metodo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string metodo = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMetodoBytes() {
      java.lang.Object ref = metodo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metodo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARGUMENTOS_FIELD_NUMBER = 5;
    private java.util.List<com.google.protobuf.ByteString> argumentos_;
    /**
     * <code>repeated bytes argumentos = 5;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getArgumentosList() {
      return argumentos_;
    }
    /**
     * <code>repeated bytes argumentos = 5;</code>
     */
    public int getArgumentosCount() {
      return argumentos_.size();
    }
    /**
     * <code>repeated bytes argumentos = 5;</code>
     */
    public com.google.protobuf.ByteString getArgumentos(int index) {
      return argumentos_.get(index);
    }

    private void initFields() {
      tipo_ = 0;
      id_ = 0;
      objeto_ = "";
      metodo_ = "";
      argumentos_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTipo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasObjeto()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMetodo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, tipo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getObjetoBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getMetodoBytes());
      }
      for (int i = 0; i < argumentos_.size(); i++) {
        output.writeBytes(5, argumentos_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, tipo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getObjetoBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getMetodoBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < argumentos_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(argumentos_.get(i));
        }
        size += dataSize;
        size += 1 * getArgumentosList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Message.Mensagem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message.Mensagem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message.Mensagem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message.Mensagem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message.Mensagem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Message.Mensagem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Message.Mensagem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Message.Mensagem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Message.Mensagem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Message.Mensagem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Message.Mensagem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Mensagem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Mensagem)
        Message.MensagemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Message.internal_static_Mensagem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Message.internal_static_Mensagem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Message.Mensagem.class, Message.Mensagem.Builder.class);
      }

      // Construct using Message.Mensagem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        tipo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        objeto_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        metodo_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        argumentos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Message.internal_static_Mensagem_descriptor;
      }

      public Message.Mensagem getDefaultInstanceForType() {
        return Message.Mensagem.getDefaultInstance();
      }

      public Message.Mensagem build() {
        Message.Mensagem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Message.Mensagem buildPartial() {
        Message.Mensagem result = new Message.Mensagem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tipo_ = tipo_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.objeto_ = objeto_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.metodo_ = metodo_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          argumentos_ = java.util.Collections.unmodifiableList(argumentos_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.argumentos_ = argumentos_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Message.Mensagem) {
          return mergeFrom((Message.Mensagem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Message.Mensagem other) {
        if (other == Message.Mensagem.getDefaultInstance()) return this;
        if (other.hasTipo()) {
          setTipo(other.getTipo());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasObjeto()) {
          bitField0_ |= 0x00000004;
          objeto_ = other.objeto_;
          onChanged();
        }
        if (other.hasMetodo()) {
          bitField0_ |= 0x00000008;
          metodo_ = other.metodo_;
          onChanged();
        }
        if (!other.argumentos_.isEmpty()) {
          if (argumentos_.isEmpty()) {
            argumentos_ = other.argumentos_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureArgumentosIsMutable();
            argumentos_.addAll(other.argumentos_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTipo()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        if (!hasObjeto()) {
          
          return false;
        }
        if (!hasMetodo()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Message.Mensagem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Message.Mensagem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int tipo_ ;
      /**
       * <code>required int32 tipo = 1;</code>
       */
      public boolean hasTipo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 tipo = 1;</code>
       */
      public int getTipo() {
        return tipo_;
      }
      /**
       * <code>required int32 tipo = 1;</code>
       */
      public Builder setTipo(int value) {
        bitField0_ |= 0x00000001;
        tipo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 tipo = 1;</code>
       */
      public Builder clearTipo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tipo_ = 0;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>required int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object objeto_ = "";
      /**
       * <code>required string objeto = 3;</code>
       */
      public boolean hasObjeto() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string objeto = 3;</code>
       */
      public java.lang.String getObjeto() {
        java.lang.Object ref = objeto_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            objeto_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string objeto = 3;</code>
       */
      public com.google.protobuf.ByteString
          getObjetoBytes() {
        java.lang.Object ref = objeto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          objeto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string objeto = 3;</code>
       */
      public Builder setObjeto(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        objeto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string objeto = 3;</code>
       */
      public Builder clearObjeto() {
        bitField0_ = (bitField0_ & ~0x00000004);
        objeto_ = getDefaultInstance().getObjeto();
        onChanged();
        return this;
      }
      /**
       * <code>required string objeto = 3;</code>
       */
      public Builder setObjetoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        objeto_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object metodo_ = "";
      /**
       * <code>required string metodo = 4;</code>
       */
      public boolean hasMetodo() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string metodo = 4;</code>
       */
      public java.lang.String getMetodo() {
        java.lang.Object ref = metodo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            metodo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string metodo = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMetodoBytes() {
        java.lang.Object ref = metodo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          metodo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string metodo = 4;</code>
       */
      public Builder setMetodo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        metodo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string metodo = 4;</code>
       */
      public Builder clearMetodo() {
        bitField0_ = (bitField0_ & ~0x00000008);
        metodo_ = getDefaultInstance().getMetodo();
        onChanged();
        return this;
      }
      /**
       * <code>required string metodo = 4;</code>
       */
      public Builder setMetodoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        metodo_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> argumentos_ = java.util.Collections.emptyList();
      private void ensureArgumentosIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          argumentos_ = new java.util.ArrayList<com.google.protobuf.ByteString>(argumentos_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated bytes argumentos = 5;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getArgumentosList() {
        return java.util.Collections.unmodifiableList(argumentos_);
      }
      /**
       * <code>repeated bytes argumentos = 5;</code>
       */
      public int getArgumentosCount() {
        return argumentos_.size();
      }
      /**
       * <code>repeated bytes argumentos = 5;</code>
       */
      public com.google.protobuf.ByteString getArgumentos(int index) {
        return argumentos_.get(index);
      }
      /**
       * <code>repeated bytes argumentos = 5;</code>
       */
      public Builder setArgumentos(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArgumentosIsMutable();
        argumentos_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes argumentos = 5;</code>
       */
      public Builder addArgumentos(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArgumentosIsMutable();
        argumentos_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes argumentos = 5;</code>
       */
      public Builder addAllArgumentos(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureArgumentosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, argumentos_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes argumentos = 5;</code>
       */
      public Builder clearArgumentos() {
        argumentos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Mensagem)
    }

    static {
      defaultInstance = new Mensagem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Mensagem)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Mensagem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Mensagem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016mensagem.proto\"X\n\010Mensagem\022\014\n\004tipo\030\001 \002" +
      "(\005\022\n\n\002id\030\002 \002(\005\022\016\n\006objeto\030\003 \002(\t\022\016\n\006metodo" +
      "\030\004 \002(\t\022\022\n\nargumentos\030\005 \003(\014B\tB\007Message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Mensagem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Mensagem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Mensagem_descriptor,
        new java.lang.String[] { "Tipo", "Id", "Objeto", "Metodo", "Argumentos", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
