package br.ufc.model;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rotas.proto

public final class Rotas {
  private Rotas() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PassoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Passo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string instrucao = 1;</code>
     */
    boolean hasInstrucao();
    /**
     * <code>required string instrucao = 1;</code>
     */
    java.lang.String getInstrucao();
    /**
     * <code>required string instrucao = 1;</code>
     */
    com.google.protobuf.ByteString
        getInstrucaoBytes();

    /**
     * <code>required string distancia = 2;</code>
     */
    boolean hasDistancia();
    /**
     * <code>required string distancia = 2;</code>
     */
    java.lang.String getDistancia();
    /**
     * <code>required string distancia = 2;</code>
     */
    com.google.protobuf.ByteString
        getDistanciaBytes();

    /**
     * <code>required string tempo = 3;</code>
     */
    boolean hasTempo();
    /**
     * <code>required string tempo = 3;</code>
     */
    java.lang.String getTempo();
    /**
     * <code>required string tempo = 3;</code>
     */
    com.google.protobuf.ByteString
        getTempoBytes();
  }
  /**
   * Protobuf type {@code Passo}
   */
  public static final class Passo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Passo)
      PassoOrBuilder {
    // Use Passo.newBuilder() to construct.
    private Passo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Passo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Passo defaultInstance;
    public static Passo getDefaultInstance() {
      return defaultInstance;
    }

    public Passo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Passo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              instrucao_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              distancia_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              tempo_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Rotas.internal_static_Passo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Rotas.internal_static_Passo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Rotas.Passo.class, Rotas.Passo.Builder.class);
    }

    public static com.google.protobuf.Parser<Passo> PARSER =
        new com.google.protobuf.AbstractParser<Passo>() {
      public Passo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Passo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Passo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int INSTRUCAO_FIELD_NUMBER = 1;
    private java.lang.Object instrucao_;
    /**
     * <code>required string instrucao = 1;</code>
     */
    public boolean hasInstrucao() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string instrucao = 1;</code>
     */
    public java.lang.String getInstrucao() {
      java.lang.Object ref = instrucao_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          instrucao_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string instrucao = 1;</code>
     */
    public com.google.protobuf.ByteString
        getInstrucaoBytes() {
      java.lang.Object ref = instrucao_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instrucao_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISTANCIA_FIELD_NUMBER = 2;
    private java.lang.Object distancia_;
    /**
     * <code>required string distancia = 2;</code>
     */
    public boolean hasDistancia() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string distancia = 2;</code>
     */
    public java.lang.String getDistancia() {
      java.lang.Object ref = distancia_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          distancia_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string distancia = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDistanciaBytes() {
      java.lang.Object ref = distancia_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        distancia_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEMPO_FIELD_NUMBER = 3;
    private java.lang.Object tempo_;
    /**
     * <code>required string tempo = 3;</code>
     */
    public boolean hasTempo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string tempo = 3;</code>
     */
    public java.lang.String getTempo() {
      java.lang.Object ref = tempo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tempo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string tempo = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTempoBytes() {
      java.lang.Object ref = tempo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tempo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      instrucao_ = "";
      distancia_ = "";
      tempo_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasInstrucao()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDistancia()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTempo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getInstrucaoBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDistanciaBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTempoBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getInstrucaoBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDistanciaBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTempoBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Rotas.Passo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Rotas.Passo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Rotas.Passo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Rotas.Passo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Rotas.Passo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Rotas.Passo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Rotas.Passo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Rotas.Passo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Rotas.Passo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Rotas.Passo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Rotas.Passo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Passo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Passo)
        Rotas.PassoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Rotas.internal_static_Passo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Rotas.internal_static_Passo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Rotas.Passo.class, Rotas.Passo.Builder.class);
      }

      // Construct using Rotas.Passo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        instrucao_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        distancia_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        tempo_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Rotas.internal_static_Passo_descriptor;
      }

      public Rotas.Passo getDefaultInstanceForType() {
        return Rotas.Passo.getDefaultInstance();
      }

      public Rotas.Passo build() {
        Rotas.Passo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Rotas.Passo buildPartial() {
        Rotas.Passo result = new Rotas.Passo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.instrucao_ = instrucao_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.distancia_ = distancia_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.tempo_ = tempo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Rotas.Passo) {
          return mergeFrom((Rotas.Passo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Rotas.Passo other) {
        if (other == Rotas.Passo.getDefaultInstance()) return this;
        if (other.hasInstrucao()) {
          bitField0_ |= 0x00000001;
          instrucao_ = other.instrucao_;
          onChanged();
        }
        if (other.hasDistancia()) {
          bitField0_ |= 0x00000002;
          distancia_ = other.distancia_;
          onChanged();
        }
        if (other.hasTempo()) {
          bitField0_ |= 0x00000004;
          tempo_ = other.tempo_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasInstrucao()) {
          
          return false;
        }
        if (!hasDistancia()) {
          
          return false;
        }
        if (!hasTempo()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Rotas.Passo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Rotas.Passo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object instrucao_ = "";
      /**
       * <code>required string instrucao = 1;</code>
       */
      public boolean hasInstrucao() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string instrucao = 1;</code>
       */
      public java.lang.String getInstrucao() {
        java.lang.Object ref = instrucao_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            instrucao_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string instrucao = 1;</code>
       */
      public com.google.protobuf.ByteString
          getInstrucaoBytes() {
        java.lang.Object ref = instrucao_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          instrucao_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string instrucao = 1;</code>
       */
      public Builder setInstrucao(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        instrucao_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string instrucao = 1;</code>
       */
      public Builder clearInstrucao() {
        bitField0_ = (bitField0_ & ~0x00000001);
        instrucao_ = getDefaultInstance().getInstrucao();
        onChanged();
        return this;
      }
      /**
       * <code>required string instrucao = 1;</code>
       */
      public Builder setInstrucaoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        instrucao_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object distancia_ = "";
      /**
       * <code>required string distancia = 2;</code>
       */
      public boolean hasDistancia() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string distancia = 2;</code>
       */
      public java.lang.String getDistancia() {
        java.lang.Object ref = distancia_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            distancia_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string distancia = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDistanciaBytes() {
        java.lang.Object ref = distancia_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          distancia_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string distancia = 2;</code>
       */
      public Builder setDistancia(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        distancia_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string distancia = 2;</code>
       */
      public Builder clearDistancia() {
        bitField0_ = (bitField0_ & ~0x00000002);
        distancia_ = getDefaultInstance().getDistancia();
        onChanged();
        return this;
      }
      /**
       * <code>required string distancia = 2;</code>
       */
      public Builder setDistanciaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        distancia_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tempo_ = "";
      /**
       * <code>required string tempo = 3;</code>
       */
      public boolean hasTempo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string tempo = 3;</code>
       */
      public java.lang.String getTempo() {
        java.lang.Object ref = tempo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tempo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string tempo = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTempoBytes() {
        java.lang.Object ref = tempo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tempo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string tempo = 3;</code>
       */
      public Builder setTempo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        tempo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string tempo = 3;</code>
       */
      public Builder clearTempo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        tempo_ = getDefaultInstance().getTempo();
        onChanged();
        return this;
      }
      /**
       * <code>required string tempo = 3;</code>
       */
      public Builder setTempoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        tempo_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Passo)
    }

    static {
      defaultInstance = new Passo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Passo)
  }

  public interface RotaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Rota)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string enderecoOrigem = 2;</code>
     */
    boolean hasEnderecoOrigem();
    /**
     * <code>required string enderecoOrigem = 2;</code>
     */
    java.lang.String getEnderecoOrigem();
    /**
     * <code>required string enderecoOrigem = 2;</code>
     */
    com.google.protobuf.ByteString
        getEnderecoOrigemBytes();

    /**
     * <code>required string enderecoDestino = 3;</code>
     */
    boolean hasEnderecoDestino();
    /**
     * <code>required string enderecoDestino = 3;</code>
     */
    java.lang.String getEnderecoDestino();
    /**
     * <code>required string enderecoDestino = 3;</code>
     */
    com.google.protobuf.ByteString
        getEnderecoDestinoBytes();

    /**
     * <code>required string tamanho = 4;</code>
     */
    boolean hasTamanho();
    /**
     * <code>required string tamanho = 4;</code>
     */
    java.lang.String getTamanho();
    /**
     * <code>required string tamanho = 4;</code>
     */
    com.google.protobuf.ByteString
        getTamanhoBytes();

    /**
     * <code>repeated .Passo passo = 5;</code>
     */
    java.util.List<Rotas.Passo> 
        getPassoList();
    /**
     * <code>repeated .Passo passo = 5;</code>
     */
    Rotas.Passo getPasso(int index);
    /**
     * <code>repeated .Passo passo = 5;</code>
     */
    int getPassoCount();
    /**
     * <code>repeated .Passo passo = 5;</code>
     */
    java.util.List<? extends Rotas.PassoOrBuilder> 
        getPassoOrBuilderList();
    /**
     * <code>repeated .Passo passo = 5;</code>
     */
    Rotas.PassoOrBuilder getPassoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Rota}
   */
  public static final class Rota extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Rota)
      RotaOrBuilder {
    // Use Rota.newBuilder() to construct.
    private Rota(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Rota(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Rota defaultInstance;
    public static Rota getDefaultInstance() {
      return defaultInstance;
    }

    public Rota getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Rota(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              enderecoOrigem_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              enderecoDestino_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              tamanho_ = bs;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                passo_ = new java.util.ArrayList<Rotas.Passo>();
                mutable_bitField0_ |= 0x00000008;
              }
              passo_.add(input.readMessage(Rotas.Passo.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          passo_ = java.util.Collections.unmodifiableList(passo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Rotas.internal_static_Rota_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Rotas.internal_static_Rota_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Rotas.Rota.class, Rotas.Rota.Builder.class);
    }

    public static com.google.protobuf.Parser<Rota> PARSER =
        new com.google.protobuf.AbstractParser<Rota>() {
      public Rota parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Rota(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Rota> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ENDERECOORIGEM_FIELD_NUMBER = 2;
    private java.lang.Object enderecoOrigem_;
    /**
     * <code>required string enderecoOrigem = 2;</code>
     */
    public boolean hasEnderecoOrigem() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string enderecoOrigem = 2;</code>
     */
    public java.lang.String getEnderecoOrigem() {
      java.lang.Object ref = enderecoOrigem_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          enderecoOrigem_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string enderecoOrigem = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEnderecoOrigemBytes() {
      java.lang.Object ref = enderecoOrigem_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        enderecoOrigem_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENDERECODESTINO_FIELD_NUMBER = 3;
    private java.lang.Object enderecoDestino_;
    /**
     * <code>required string enderecoDestino = 3;</code>
     */
    public boolean hasEnderecoDestino() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string enderecoDestino = 3;</code>
     */
    public java.lang.String getEnderecoDestino() {
      java.lang.Object ref = enderecoDestino_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          enderecoDestino_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string enderecoDestino = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEnderecoDestinoBytes() {
      java.lang.Object ref = enderecoDestino_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        enderecoDestino_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAMANHO_FIELD_NUMBER = 4;
    private java.lang.Object tamanho_;
    /**
     * <code>required string tamanho = 4;</code>
     */
    public boolean hasTamanho() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string tamanho = 4;</code>
     */
    public java.lang.String getTamanho() {
      java.lang.Object ref = tamanho_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tamanho_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string tamanho = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTamanhoBytes() {
      java.lang.Object ref = tamanho_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tamanho_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSO_FIELD_NUMBER = 5;
    private java.util.List<Rotas.Passo> passo_;
    /**
     * <code>repeated .Passo passo = 5;</code>
     */
    public java.util.List<Rotas.Passo> getPassoList() {
      return passo_;
    }
    /**
     * <code>repeated .Passo passo = 5;</code>
     */
    public java.util.List<? extends Rotas.PassoOrBuilder> 
        getPassoOrBuilderList() {
      return passo_;
    }
    /**
     * <code>repeated .Passo passo = 5;</code>
     */
    public int getPassoCount() {
      return passo_.size();
    }
    /**
     * <code>repeated .Passo passo = 5;</code>
     */
    public Rotas.Passo getPasso(int index) {
      return passo_.get(index);
    }
    /**
     * <code>repeated .Passo passo = 5;</code>
     */
    public Rotas.PassoOrBuilder getPassoOrBuilder(
        int index) {
      return passo_.get(index);
    }

    private void initFields() {
      enderecoOrigem_ = "";
      enderecoDestino_ = "";
      tamanho_ = "";
      passo_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasEnderecoOrigem()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEnderecoDestino()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTamanho()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPassoCount(); i++) {
        if (!getPasso(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getEnderecoOrigemBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getEnderecoDestinoBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, getTamanhoBytes());
      }
      for (int i = 0; i < passo_.size(); i++) {
        output.writeMessage(5, passo_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getEnderecoOrigemBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEnderecoDestinoBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTamanhoBytes());
      }
      for (int i = 0; i < passo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, passo_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Rotas.Rota parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Rotas.Rota parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Rotas.Rota parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Rotas.Rota parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Rotas.Rota parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Rotas.Rota parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Rotas.Rota parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Rotas.Rota parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Rotas.Rota parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Rotas.Rota parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Rotas.Rota prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Rota}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Rota)
        Rotas.RotaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Rotas.internal_static_Rota_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Rotas.internal_static_Rota_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Rotas.Rota.class, Rotas.Rota.Builder.class);
      }

      // Construct using Rotas.Rota.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPassoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        enderecoOrigem_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        enderecoDestino_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        tamanho_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (passoBuilder_ == null) {
          passo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          passoBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Rotas.internal_static_Rota_descriptor;
      }

      public Rotas.Rota getDefaultInstanceForType() {
        return Rotas.Rota.getDefaultInstance();
      }

      public Rotas.Rota build() {
        Rotas.Rota result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Rotas.Rota buildPartial() {
        Rotas.Rota result = new Rotas.Rota(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.enderecoOrigem_ = enderecoOrigem_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.enderecoDestino_ = enderecoDestino_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.tamanho_ = tamanho_;
        if (passoBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            passo_ = java.util.Collections.unmodifiableList(passo_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.passo_ = passo_;
        } else {
          result.passo_ = passoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Rotas.Rota) {
          return mergeFrom((Rotas.Rota)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Rotas.Rota other) {
        if (other == Rotas.Rota.getDefaultInstance()) return this;
        if (other.hasEnderecoOrigem()) {
          bitField0_ |= 0x00000001;
          enderecoOrigem_ = other.enderecoOrigem_;
          onChanged();
        }
        if (other.hasEnderecoDestino()) {
          bitField0_ |= 0x00000002;
          enderecoDestino_ = other.enderecoDestino_;
          onChanged();
        }
        if (other.hasTamanho()) {
          bitField0_ |= 0x00000004;
          tamanho_ = other.tamanho_;
          onChanged();
        }
        if (passoBuilder_ == null) {
          if (!other.passo_.isEmpty()) {
            if (passo_.isEmpty()) {
              passo_ = other.passo_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensurePassoIsMutable();
              passo_.addAll(other.passo_);
            }
            onChanged();
          }
        } else {
          if (!other.passo_.isEmpty()) {
            if (passoBuilder_.isEmpty()) {
              passoBuilder_.dispose();
              passoBuilder_ = null;
              passo_ = other.passo_;
              bitField0_ = (bitField0_ & ~0x00000008);
              passoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPassoFieldBuilder() : null;
            } else {
              passoBuilder_.addAllMessages(other.passo_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEnderecoOrigem()) {
          
          return false;
        }
        if (!hasEnderecoDestino()) {
          
          return false;
        }
        if (!hasTamanho()) {
          
          return false;
        }
        for (int i = 0; i < getPassoCount(); i++) {
          if (!getPasso(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Rotas.Rota parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Rotas.Rota) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object enderecoOrigem_ = "";
      /**
       * <code>required string enderecoOrigem = 2;</code>
       */
      public boolean hasEnderecoOrigem() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string enderecoOrigem = 2;</code>
       */
      public java.lang.String getEnderecoOrigem() {
        java.lang.Object ref = enderecoOrigem_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            enderecoOrigem_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string enderecoOrigem = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEnderecoOrigemBytes() {
        java.lang.Object ref = enderecoOrigem_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          enderecoOrigem_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string enderecoOrigem = 2;</code>
       */
      public Builder setEnderecoOrigem(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        enderecoOrigem_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string enderecoOrigem = 2;</code>
       */
      public Builder clearEnderecoOrigem() {
        bitField0_ = (bitField0_ & ~0x00000001);
        enderecoOrigem_ = getDefaultInstance().getEnderecoOrigem();
        onChanged();
        return this;
      }
      /**
       * <code>required string enderecoOrigem = 2;</code>
       */
      public Builder setEnderecoOrigemBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        enderecoOrigem_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object enderecoDestino_ = "";
      /**
       * <code>required string enderecoDestino = 3;</code>
       */
      public boolean hasEnderecoDestino() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string enderecoDestino = 3;</code>
       */
      public java.lang.String getEnderecoDestino() {
        java.lang.Object ref = enderecoDestino_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            enderecoDestino_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string enderecoDestino = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEnderecoDestinoBytes() {
        java.lang.Object ref = enderecoDestino_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          enderecoDestino_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string enderecoDestino = 3;</code>
       */
      public Builder setEnderecoDestino(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        enderecoDestino_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string enderecoDestino = 3;</code>
       */
      public Builder clearEnderecoDestino() {
        bitField0_ = (bitField0_ & ~0x00000002);
        enderecoDestino_ = getDefaultInstance().getEnderecoDestino();
        onChanged();
        return this;
      }
      /**
       * <code>required string enderecoDestino = 3;</code>
       */
      public Builder setEnderecoDestinoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        enderecoDestino_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tamanho_ = "";
      /**
       * <code>required string tamanho = 4;</code>
       */
      public boolean hasTamanho() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string tamanho = 4;</code>
       */
      public java.lang.String getTamanho() {
        java.lang.Object ref = tamanho_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tamanho_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string tamanho = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTamanhoBytes() {
        java.lang.Object ref = tamanho_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tamanho_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string tamanho = 4;</code>
       */
      public Builder setTamanho(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        tamanho_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string tamanho = 4;</code>
       */
      public Builder clearTamanho() {
        bitField0_ = (bitField0_ & ~0x00000004);
        tamanho_ = getDefaultInstance().getTamanho();
        onChanged();
        return this;
      }
      /**
       * <code>required string tamanho = 4;</code>
       */
      public Builder setTamanhoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        tamanho_ = value;
        onChanged();
        return this;
      }

      private java.util.List<Rotas.Passo> passo_ =
        java.util.Collections.emptyList();
      private void ensurePassoIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          passo_ = new java.util.ArrayList<Rotas.Passo>(passo_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Rotas.Passo, Rotas.Passo.Builder, Rotas.PassoOrBuilder> passoBuilder_;

      /**
       * <code>repeated .Passo passo = 5;</code>
       */
      public java.util.List<Rotas.Passo> getPassoList() {
        if (passoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(passo_);
        } else {
          return passoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Passo passo = 5;</code>
       */
      public int getPassoCount() {
        if (passoBuilder_ == null) {
          return passo_.size();
        } else {
          return passoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Passo passo = 5;</code>
       */
      public Rotas.Passo getPasso(int index) {
        if (passoBuilder_ == null) {
          return passo_.get(index);
        } else {
          return passoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Passo passo = 5;</code>
       */
      public Builder setPasso(
          int index, Rotas.Passo value) {
        if (passoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePassoIsMutable();
          passo_.set(index, value);
          onChanged();
        } else {
          passoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Passo passo = 5;</code>
       */
      public Builder setPasso(
          int index, Rotas.Passo.Builder builderForValue) {
        if (passoBuilder_ == null) {
          ensurePassoIsMutable();
          passo_.set(index, builderForValue.build());
          onChanged();
        } else {
          passoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Passo passo = 5;</code>
       */
      public Builder addPasso(Rotas.Passo value) {
        if (passoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePassoIsMutable();
          passo_.add(value);
          onChanged();
        } else {
          passoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Passo passo = 5;</code>
       */
      public Builder addPasso(
          int index, Rotas.Passo value) {
        if (passoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePassoIsMutable();
          passo_.add(index, value);
          onChanged();
        } else {
          passoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Passo passo = 5;</code>
       */
      public Builder addPasso(
          Rotas.Passo.Builder builderForValue) {
        if (passoBuilder_ == null) {
          ensurePassoIsMutable();
          passo_.add(builderForValue.build());
          onChanged();
        } else {
          passoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Passo passo = 5;</code>
       */
      public Builder addPasso(
          int index, Rotas.Passo.Builder builderForValue) {
        if (passoBuilder_ == null) {
          ensurePassoIsMutable();
          passo_.add(index, builderForValue.build());
          onChanged();
        } else {
          passoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Passo passo = 5;</code>
       */
      public Builder addAllPasso(
          java.lang.Iterable<? extends Rotas.Passo> values) {
        if (passoBuilder_ == null) {
          ensurePassoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, passo_);
          onChanged();
        } else {
          passoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Passo passo = 5;</code>
       */
      public Builder clearPasso() {
        if (passoBuilder_ == null) {
          passo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          passoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Passo passo = 5;</code>
       */
      public Builder removePasso(int index) {
        if (passoBuilder_ == null) {
          ensurePassoIsMutable();
          passo_.remove(index);
          onChanged();
        } else {
          passoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Passo passo = 5;</code>
       */
      public Rotas.Passo.Builder getPassoBuilder(
          int index) {
        return getPassoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Passo passo = 5;</code>
       */
      public Rotas.PassoOrBuilder getPassoOrBuilder(
          int index) {
        if (passoBuilder_ == null) {
          return passo_.get(index);  } else {
          return passoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Passo passo = 5;</code>
       */
      public java.util.List<? extends Rotas.PassoOrBuilder> 
           getPassoOrBuilderList() {
        if (passoBuilder_ != null) {
          return passoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(passo_);
        }
      }
      /**
       * <code>repeated .Passo passo = 5;</code>
       */
      public Rotas.Passo.Builder addPassoBuilder() {
        return getPassoFieldBuilder().addBuilder(
            Rotas.Passo.getDefaultInstance());
      }
      /**
       * <code>repeated .Passo passo = 5;</code>
       */
      public Rotas.Passo.Builder addPassoBuilder(
          int index) {
        return getPassoFieldBuilder().addBuilder(
            index, Rotas.Passo.getDefaultInstance());
      }
      /**
       * <code>repeated .Passo passo = 5;</code>
       */
      public java.util.List<Rotas.Passo.Builder> 
           getPassoBuilderList() {
        return getPassoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Rotas.Passo, Rotas.Passo.Builder, Rotas.PassoOrBuilder> 
          getPassoFieldBuilder() {
        if (passoBuilder_ == null) {
          passoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Rotas.Passo, Rotas.Passo.Builder, Rotas.PassoOrBuilder>(
                  passo_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          passo_ = null;
        }
        return passoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Rota)
    }

    static {
      defaultInstance = new Rota(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Rota)
  }

  public interface ListaRotaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ListaRota)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Rota rota = 1;</code>
     */
    java.util.List<Rotas.Rota> 
        getRotaList();
    /**
     * <code>repeated .Rota rota = 1;</code>
     */
    Rotas.Rota getRota(int index);
    /**
     * <code>repeated .Rota rota = 1;</code>
     */
    int getRotaCount();
    /**
     * <code>repeated .Rota rota = 1;</code>
     */
    java.util.List<? extends Rotas.RotaOrBuilder> 
        getRotaOrBuilderList();
    /**
     * <code>repeated .Rota rota = 1;</code>
     */
    Rotas.RotaOrBuilder getRotaOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ListaRota}
   */
  public static final class ListaRota extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ListaRota)
      ListaRotaOrBuilder {
    // Use ListaRota.newBuilder() to construct.
    private ListaRota(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ListaRota(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ListaRota defaultInstance;
    public static ListaRota getDefaultInstance() {
      return defaultInstance;
    }

    public ListaRota getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ListaRota(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                rota_ = new java.util.ArrayList<Rotas.Rota>();
                mutable_bitField0_ |= 0x00000001;
              }
              rota_.add(input.readMessage(Rotas.Rota.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          rota_ = java.util.Collections.unmodifiableList(rota_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Rotas.internal_static_ListaRota_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Rotas.internal_static_ListaRota_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Rotas.ListaRota.class, Rotas.ListaRota.Builder.class);
    }

    public static com.google.protobuf.Parser<ListaRota> PARSER =
        new com.google.protobuf.AbstractParser<ListaRota>() {
      public ListaRota parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListaRota(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ListaRota> getParserForType() {
      return PARSER;
    }

    public static final int ROTA_FIELD_NUMBER = 1;
    private java.util.List<Rotas.Rota> rota_;
    /**
     * <code>repeated .Rota rota = 1;</code>
     */
    public java.util.List<Rotas.Rota> getRotaList() {
      return rota_;
    }
    /**
     * <code>repeated .Rota rota = 1;</code>
     */
    public java.util.List<? extends Rotas.RotaOrBuilder> 
        getRotaOrBuilderList() {
      return rota_;
    }
    /**
     * <code>repeated .Rota rota = 1;</code>
     */
    public int getRotaCount() {
      return rota_.size();
    }
    /**
     * <code>repeated .Rota rota = 1;</code>
     */
    public Rotas.Rota getRota(int index) {
      return rota_.get(index);
    }
    /**
     * <code>repeated .Rota rota = 1;</code>
     */
    public Rotas.RotaOrBuilder getRotaOrBuilder(
        int index) {
      return rota_.get(index);
    }

    private void initFields() {
      rota_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getRotaCount(); i++) {
        if (!getRota(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < rota_.size(); i++) {
        output.writeMessage(1, rota_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < rota_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, rota_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Rotas.ListaRota parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Rotas.ListaRota parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Rotas.ListaRota parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Rotas.ListaRota parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Rotas.ListaRota parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Rotas.ListaRota parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Rotas.ListaRota parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Rotas.ListaRota parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Rotas.ListaRota parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Rotas.ListaRota parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Rotas.ListaRota prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ListaRota}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ListaRota)
        Rotas.ListaRotaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Rotas.internal_static_ListaRota_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Rotas.internal_static_ListaRota_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Rotas.ListaRota.class, Rotas.ListaRota.Builder.class);
      }

      // Construct using Rotas.ListaRota.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRotaFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (rotaBuilder_ == null) {
          rota_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          rotaBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Rotas.internal_static_ListaRota_descriptor;
      }

      public Rotas.ListaRota getDefaultInstanceForType() {
        return Rotas.ListaRota.getDefaultInstance();
      }

      public Rotas.ListaRota build() {
        Rotas.ListaRota result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Rotas.ListaRota buildPartial() {
        Rotas.ListaRota result = new Rotas.ListaRota(this);
        int from_bitField0_ = bitField0_;
        if (rotaBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            rota_ = java.util.Collections.unmodifiableList(rota_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.rota_ = rota_;
        } else {
          result.rota_ = rotaBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Rotas.ListaRota) {
          return mergeFrom((Rotas.ListaRota)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Rotas.ListaRota other) {
        if (other == Rotas.ListaRota.getDefaultInstance()) return this;
        if (rotaBuilder_ == null) {
          if (!other.rota_.isEmpty()) {
            if (rota_.isEmpty()) {
              rota_ = other.rota_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRotaIsMutable();
              rota_.addAll(other.rota_);
            }
            onChanged();
          }
        } else {
          if (!other.rota_.isEmpty()) {
            if (rotaBuilder_.isEmpty()) {
              rotaBuilder_.dispose();
              rotaBuilder_ = null;
              rota_ = other.rota_;
              bitField0_ = (bitField0_ & ~0x00000001);
              rotaBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRotaFieldBuilder() : null;
            } else {
              rotaBuilder_.addAllMessages(other.rota_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getRotaCount(); i++) {
          if (!getRota(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Rotas.ListaRota parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Rotas.ListaRota) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Rotas.Rota> rota_ =
        java.util.Collections.emptyList();
      private void ensureRotaIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          rota_ = new java.util.ArrayList<Rotas.Rota>(rota_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Rotas.Rota, Rotas.Rota.Builder, Rotas.RotaOrBuilder> rotaBuilder_;

      /**
       * <code>repeated .Rota rota = 1;</code>
       */
      public java.util.List<Rotas.Rota> getRotaList() {
        if (rotaBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rota_);
        } else {
          return rotaBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Rota rota = 1;</code>
       */
      public int getRotaCount() {
        if (rotaBuilder_ == null) {
          return rota_.size();
        } else {
          return rotaBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Rota rota = 1;</code>
       */
      public Rotas.Rota getRota(int index) {
        if (rotaBuilder_ == null) {
          return rota_.get(index);
        } else {
          return rotaBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Rota rota = 1;</code>
       */
      public Builder setRota(
          int index, Rotas.Rota value) {
        if (rotaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRotaIsMutable();
          rota_.set(index, value);
          onChanged();
        } else {
          rotaBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Rota rota = 1;</code>
       */
      public Builder setRota(
          int index, Rotas.Rota.Builder builderForValue) {
        if (rotaBuilder_ == null) {
          ensureRotaIsMutable();
          rota_.set(index, builderForValue.build());
          onChanged();
        } else {
          rotaBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Rota rota = 1;</code>
       */
      public Builder addRota(Rotas.Rota value) {
        if (rotaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRotaIsMutable();
          rota_.add(value);
          onChanged();
        } else {
          rotaBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Rota rota = 1;</code>
       */
      public Builder addRota(
          int index, Rotas.Rota value) {
        if (rotaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRotaIsMutable();
          rota_.add(index, value);
          onChanged();
        } else {
          rotaBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Rota rota = 1;</code>
       */
      public Builder addRota(
          Rotas.Rota.Builder builderForValue) {
        if (rotaBuilder_ == null) {
          ensureRotaIsMutable();
          rota_.add(builderForValue.build());
          onChanged();
        } else {
          rotaBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Rota rota = 1;</code>
       */
      public Builder addRota(
          int index, Rotas.Rota.Builder builderForValue) {
        if (rotaBuilder_ == null) {
          ensureRotaIsMutable();
          rota_.add(index, builderForValue.build());
          onChanged();
        } else {
          rotaBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Rota rota = 1;</code>
       */
      public Builder addAllRota(
          java.lang.Iterable<? extends Rotas.Rota> values) {
        if (rotaBuilder_ == null) {
          ensureRotaIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rota_);
          onChanged();
        } else {
          rotaBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Rota rota = 1;</code>
       */
      public Builder clearRota() {
        if (rotaBuilder_ == null) {
          rota_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          rotaBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Rota rota = 1;</code>
       */
      public Builder removeRota(int index) {
        if (rotaBuilder_ == null) {
          ensureRotaIsMutable();
          rota_.remove(index);
          onChanged();
        } else {
          rotaBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Rota rota = 1;</code>
       */
      public Rotas.Rota.Builder getRotaBuilder(
          int index) {
        return getRotaFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Rota rota = 1;</code>
       */
      public Rotas.RotaOrBuilder getRotaOrBuilder(
          int index) {
        if (rotaBuilder_ == null) {
          return rota_.get(index);  } else {
          return rotaBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Rota rota = 1;</code>
       */
      public java.util.List<? extends Rotas.RotaOrBuilder> 
           getRotaOrBuilderList() {
        if (rotaBuilder_ != null) {
          return rotaBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rota_);
        }
      }
      /**
       * <code>repeated .Rota rota = 1;</code>
       */
      public Rotas.Rota.Builder addRotaBuilder() {
        return getRotaFieldBuilder().addBuilder(
            Rotas.Rota.getDefaultInstance());
      }
      /**
       * <code>repeated .Rota rota = 1;</code>
       */
      public Rotas.Rota.Builder addRotaBuilder(
          int index) {
        return getRotaFieldBuilder().addBuilder(
            index, Rotas.Rota.getDefaultInstance());
      }
      /**
       * <code>repeated .Rota rota = 1;</code>
       */
      public java.util.List<Rotas.Rota.Builder> 
           getRotaBuilderList() {
        return getRotaFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Rotas.Rota, Rotas.Rota.Builder, Rotas.RotaOrBuilder> 
          getRotaFieldBuilder() {
        if (rotaBuilder_ == null) {
          rotaBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Rotas.Rota, Rotas.Rota.Builder, Rotas.RotaOrBuilder>(
                  rota_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          rota_ = null;
        }
        return rotaBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ListaRota)
    }

    static {
      defaultInstance = new ListaRota(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ListaRota)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Passo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Passo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Rota_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Rota_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListaRota_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ListaRota_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013rotas.proto\"<\n\005Passo\022\021\n\tinstrucao\030\001 \002(" +
      "\t\022\021\n\tdistancia\030\002 \002(\t\022\r\n\005tempo\030\003 \002(\t\"_\n\004R" +
      "ota\022\026\n\016enderecoOrigem\030\002 \002(\t\022\027\n\017enderecoD" +
      "estino\030\003 \002(\t\022\017\n\007tamanho\030\004 \002(\t\022\025\n\005passo\030\005" +
      " \003(\0132\006.Passo\" \n\tListaRota\022\023\n\004rota\030\001 \003(\0132" +
      "\005.Rota"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Passo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Passo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Passo_descriptor,
        new java.lang.String[] { "Instrucao", "Distancia", "Tempo", });
    internal_static_Rota_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Rota_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Rota_descriptor,
        new java.lang.String[] { "EnderecoOrigem", "EnderecoDestino", "Tamanho", "Passo", });
    internal_static_ListaRota_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ListaRota_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ListaRota_descriptor,
        new java.lang.String[] { "Rota", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
